### PR TITLE
GitInput: Include deepClone option in the cache key

### LINKED ISSUE #510: deepClone option in gitInput troubles
Consider two jobsets with the same git input, one without the `deepClone` option while the other one have the `deepClone` enabled.
If the first jobset is evaluated before the second one, the second one will not have the `.git` directory since it reuses the store path of the first evaluation.

To reproduce, create two jobset with gitinput such as:
```
input of jobset 1: git-repo master
input of jobset 2: git-repo master deepClone
```
Next, evaluate jobset1 before jobset2 and check the content of the clone directory.

### PR DESCRIPTION
**Pull request by ztzg**
Without this commit, two jobsets using the same repository as input, but different `deepClone` options, end up incorrectly sharing the same "checkout" for a given (`uri`, `branch`, `revision`) tuple.  The presence or absence of `.git` is determined by the jobset execution order.

This patch adds the missing `isDeepClone` boolean to the cache key.

The database upgrade script empties the `CachedGitInputs` table, as we don't know if existing checkouts are deep clones.  Unfortunately, this generally forces rebuilds even for correct `deepClone` checkouts, as the binary contents of `.git` are not deterministic.

Fixes #510

### CODE REVIEW

File: src/sql/upgrade-76.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
+-- We don't know if existing checkouts are deep clones.  This will
+-- force a new fetch (and most likely trigger a new build for deep
+-- clones, as the binary contents of '.git' are not deterministic).
+DELETE FROM CachedGitInputs;
```
Comment (grahamc) [inline src/sql/upgrade-76.sql:4]: This freaked me out a bit but we already do this often: https://github.com/NixOS/hydra/blob/04fdb8e6e66d68d2625bdefa7f1c9d99e812c15b/src/lib/Hydra/Controller/Admin.pm#L51-L59

**Review by grahamc — APPROVED** [review]
lgtm, but I'd like another set of eyes on it.

I applied this diff to hydra.nixos.org's database and the migration went smoothly, nice.

**Review by cole-h — APPROVED** [review]
Diff LGTM as well.

**Comment by ztzg** [comment]
Hi Graham,

>> @@ -0,0 +1,12 @@
> +-- We don't know if existing checkouts are deep clones.  This will
> +-- force a new fetch (and most likely trigger a new build for deep
> +-- clones, as the binary contents of '.git' are not deterministic).
> +DELETE FROM CachedGitInputs;
>
> This freaked me out a bit but we already do this often:
> https://github.com/NixOS/hydra/blob/04fdb8e6e66d68d2625bdefa7f1c9d99e812c15b/src/lib/Hydra/Controller/Admin.pm#L51-L59

Right: that tidbit is what convinced me that it was okay to clear the
table; I should have referenced it from the comment.

> Merged #976 into master.

Thanks!

Cheers, -D
