### PR TITLE
Projects: delete: delete all builds first

### LINKED ISSUE #1081: Cannot delete project due to foriegn key constraint
```
09:39:53 postgres.1           | 2021-12-20 09:39:53.903 PST [1558864] ERROR:  update or delete on table "jobsets" violates foreign key constraint "buildmetrics_project_fkey1" on table "buildmetrics"
09:39:53 postgres.1           | 2021-12-20 09:39:53.903 PST [1558864] DETAIL:  Key (project, name)=(a, patchelf) is still referenced from table "buildmetrics".
09:39:53 postgres.1           | 2021-12-20 09:39:53.903 PST [1558864] STATEMENT:  DELETE FROM jobsets WHERE ( project = $1 )
```

### PR DESCRIPTION
**Pull request by grahamc**
Deleting jobsets first would fail because buildmetrics has an FK
to the jobset. However, the jobset / project relationship is not
marked as CASCADE.

Deleting all the builds automatically cascades to delete
buildmetrics, so deleting the relevant builds first, then deleting
the jobset solves it.

Closes #1081 

cc @dasJ @ajs124 @cole-h

### CODE REVIEW

**Comment by ajs124** [comment]
Is this #1081?

**Comment by grahamc** [comment]
Nice, yep: closes #1081.

File: src/lib/Hydra/Controller/Project.pm [hunk 1]
```diff
@@ -78,8 +78,8 @@ sub project_DELETE {
     requireProjectOwner($c, $c->stash->{project});
 
     $c->model('DB')->schema->txn_do(sub {
-        $c->stash->{project}->jobsets->delete;
```
Comment (cole-h) [inline src/lib/Hydra/Controller/Project.pm:81]: How "fun" that such a simple change in ordering fixes this issue :)

**Review by cole-h — APPROVED** [review]
Woo!
