### PR TITLE
Broken constituents: emit useful log messages on evaluation errors on constituents

### LINKED ISSUE #1090: Evaluation failures of constituents causes inscrutible errors
Failure to evaluate a constituent cause an error which has no relationship to the origin of failure.

```
1{UNKNOWN}: Died at /nix/store/bj4ihx5hnmb51isf59j869wc1mhxqs28-hydra-0.1.20211223.76962bf/bin/.hydra-eval-jobset-wrapped line 779. at /nix/store/w6an5b9802y52k4x2d1cj3ngyx35mfsn-hydra-perl-deps/lib/perl5/site_perl/5.34.0/Catalyst/Model/DBIC/Schema.pm line 526
```

Would be great to have a better user UX, at least something similar to the existing jobs + eval errors format.

Would make troubleshooting failures from PRs like https://github.com/NixOS/nixpkgs/pull/152505 much easier to diagnose.

### PR DESCRIPTION
**Pull request by grahamc**
Closes #1090.

Changes:

> 1{UNKNOWN}: Died at /nix/store/bj4ihx5hnmb51isf59j869wc1mhxqs28-hydra-0.1.20211223.76962bf/bin/.hydra-eval-jobset-wrapped line 779. at /nix/store/w6an5b9802y52k4x2d1cj3ngyx35mfsn-hydra-perl-deps/lib/perl5/site_perl/5.34.0/Catalyst/Model/DBIC/Schema.pm line 526

to:

> {UNKNOWN}: aggregate job ‘mixed_aggregate’ failed with the error: constituentA: does not exist at xxx

### CODE REVIEW

File: src/script/hydra-eval-jobset [hunk 1]
```diff
@@ -799,7 +799,13 @@ sub checkJobsetWrapped {
 
             foreach my $job (values %{$jobs}) {
                 next unless $job->{constituents};
-                my $x = $drvPathToId{$job->{drvPath}} or die;
+
+                if (defined $job->{error}) {
+                    die "aggregate job ‘$job->{jobName}’ failed with the error: $job->{error}";
```
Comment (cole-h) [inline src/script/hydra-eval-jobset:804]: Should this also have a final `\n`?

File: t/lib/HydraTestContext.pm [hunk 2]
```diff
@@ -145,10 +145,47 @@ sub nix_state_dir {
 sub makeAndEvaluateJobset {
     my ($self, %opts) = @_;
 
-    my $expression = $opts{'expression'} || die "Mandatory 'expression' option not passed to makeAndEValuateJobset.";
-    my $should_build = $opts{'build'} // 0;
+    my $expression = $opts{'expression'} || die "Mandatory 'expression' option not passed to makeAndEvaluateJobset.";
```
Comment (cole-h) [inline t/lib/HydraTestContext.pm:148]: Same here -- should the `die` end with a `\n`?

File: t/lib/HydraTestContext.pm [hunk 3]
```diff
@@ -145,10 +145,47 @@ sub nix_state_dir {
...
     my $jobsdir = $opts{'jobsdir'} // $self->jobsdir;
+    my $should_build = $opts{'build'} // 0;
+
+    my $jobsetCtx = $self->makeJobset(
+        expression => $expression,
+        jobsdir => $jobsdir,
+    );
+    my $jobset = $jobsetCtx->{"jobset"};
+
+    evalSucceeds($jobset) or die "Evaluating jobs/$expression should exit with return code 0";
```
Comment (cole-h) [inline t/lib/HydraTestContext.pm:158]: Here too (and all the other `die`s below).

**Review by cole-h — APPROVED** [review]
LGTM, just some nits with regards to ending newlines (if it makes a difference).

Tests pass locally :)

File: src/script/hydra-eval-jobset (hunk 1 above)
Comment (grahamc) [reply src/script/hydra-eval-jobset:804]: Good catch, yes.

**Comment by grahamc** [comment]
Thanks, @cole-h - I've fixed that \n, and all the \n's in HydraTestContext.

**Review by cole-h — APPROVED** [review]
